name: Preview

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: Preview # Required for picking correct environment secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read NodeJS version from .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Graphql codegen
        env:
          VITE_GRAPHQL_API_URL: ${{ secrets.VITE_GRAPHQL_API_URL }}
        run: npm run codegen

      - name: Generate types for scss variables in js
        run: npm run typed-scss-modules

      - name: Linter check
        run: npm run lint

      - name: Typescript check
        run: npm run typecheck

      - name: Unit tests
        run: npm run test -- --silent
