name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: Preview # Required for picking correct environment secrets
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:check

      - name: Check for typescript errors
        run: npm run ts:check

      - name: Run tests
        env:
          VITE_GRAPHQL_API_URL: ${{ secrets.VITE_GRAPHQL_API_URL }}
        run: npm run test
